/*
 Navicat Premium Data Transfer

 Source Server         : Ervelia
 Source Server Type    : MySQL
 Source Server Version : 50733
 Source Host           : localhost:3306
 Source Schema         : information_schema

 Target Server Type    : MySQL
 Target Server Version : 50733
 File Encoding         : 65001

 Date: 08/05/2022 14:50:27
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for CHARACTER_SETS
-- ----------------------------
DROP TABLE IF EXISTS `CHARACTER_SETS`;
CREATE TABLE `CHARACTER_SETS`  (
  `CHARACTER_SET_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DEFAULT_COLLATE_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DESCRIPTION` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `MAXLEN` bigint(3) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for COLLATIONS
-- ----------------------------
DROP TABLE IF EXISTS `COLLATIONS`;
CREATE TABLE `COLLATIONS`  (
  `COLLATION_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_SET_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ID` bigint(11) NOT NULL DEFAULT 0,
  `IS_DEFAULT` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_COMPILED` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SORTLEN` bigint(3) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for COLLATION_CHARACTER_SET_APPLICABILITY
-- ----------------------------
DROP TABLE IF EXISTS `COLLATION_CHARACTER_SET_APPLICABILITY`;
CREATE TABLE `COLLATION_CHARACTER_SET_APPLICABILITY`  (
  `COLLATION_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_SET_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for COLUMNS
-- ----------------------------
DROP TABLE IF EXISTS `COLUMNS`;
CREATE TABLE `COLUMNS`  (
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLUMN_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ORDINAL_POSITION` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `COLUMN_DEFAULT` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `IS_NULLABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DATA_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `NUMERIC_PRECISION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `NUMERIC_SCALE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `DATETIME_PRECISION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CHARACTER_SET_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COLLATION_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COLUMN_TYPE` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `COLUMN_KEY` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EXTRA` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PRIVILEGES` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLUMN_COMMENT` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `GENERATION_EXPRESSION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for COLUMN_PRIVILEGES
-- ----------------------------
DROP TABLE IF EXISTS `COLUMN_PRIVILEGES`;
CREATE TABLE `COLUMN_PRIVILEGES`  (
  `GRANTEE` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLUMN_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_GRANTABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for ENGINES
-- ----------------------------
DROP TABLE IF EXISTS `ENGINES`;
CREATE TABLE `ENGINES`  (
  `ENGINE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SUPPORT` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COMMENT` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TRANSACTIONS` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `XA` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SAVEPOINTS` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for EVENTS
-- ----------------------------
DROP TABLE IF EXISTS `EVENTS`;
CREATE TABLE `EVENTS`  (
  `EVENT_CATALOG` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DEFINER` varchar(93) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TIME_ZONE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_BODY` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_DEFINITION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `EVENT_TYPE` varchar(9) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EXECUTE_AT` datetime NULL DEFAULT NULL,
  `INTERVAL_VALUE` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INTERVAL_FIELD` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SQL_MODE` varchar(8192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `STARTS` datetime NULL DEFAULT NULL,
  `ENDS` datetime NULL DEFAULT NULL,
  `STATUS` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ON_COMPLETION` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CREATED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_ALTERED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_EXECUTED` datetime NULL DEFAULT NULL,
  `EVENT_COMMENT` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ORIGINATOR` bigint(10) NOT NULL DEFAULT 0,
  `CHARACTER_SET_CLIENT` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DATABASE_COLLATION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for FILES
-- ----------------------------
DROP TABLE IF EXISTS `FILES`;
CREATE TABLE `FILES`  (
  `FILE_ID` bigint(4) NOT NULL DEFAULT 0,
  `FILE_NAME` varchar(4000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FILE_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLESPACE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TABLE_CATALOG` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LOGFILE_GROUP_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LOGFILE_GROUP_NUMBER` bigint(4) NULL DEFAULT NULL,
  `ENGINE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FULLTEXT_KEYS` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DELETED_ROWS` bigint(4) NULL DEFAULT NULL,
  `UPDATE_COUNT` bigint(4) NULL DEFAULT NULL,
  `FREE_EXTENTS` bigint(4) NULL DEFAULT NULL,
  `TOTAL_EXTENTS` bigint(4) NULL DEFAULT NULL,
  `EXTENT_SIZE` bigint(4) NOT NULL DEFAULT 0,
  `INITIAL_SIZE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `MAXIMUM_SIZE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `AUTOEXTEND_SIZE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CREATION_TIME` datetime NULL DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime NULL DEFAULT NULL,
  `LAST_ACCESS_TIME` datetime NULL DEFAULT NULL,
  `RECOVER_TIME` bigint(4) NULL DEFAULT NULL,
  `TRANSACTION_COUNTER` bigint(4) NULL DEFAULT NULL,
  `VERSION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `ROW_FORMAT` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TABLE_ROWS` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `AVG_ROW_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `MAX_DATA_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `INDEX_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_FREE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CREATE_TIME` datetime NULL DEFAULT NULL,
  `UPDATE_TIME` datetime NULL DEFAULT NULL,
  `CHECK_TIME` datetime NULL DEFAULT NULL,
  `CHECKSUM` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EXTRA` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for GLOBAL_STATUS
-- ----------------------------
DROP TABLE IF EXISTS `GLOBAL_STATUS`;
CREATE TABLE `GLOBAL_STATUS`  (
  `VARIABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `VARIABLE_VALUE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for GLOBAL_VARIABLES
-- ----------------------------
DROP TABLE IF EXISTS `GLOBAL_VARIABLES`;
CREATE TABLE `GLOBAL_VARIABLES`  (
  `VARIABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `VARIABLE_VALUE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for KEY_COLUMN_USAGE
-- ----------------------------
DROP TABLE IF EXISTS `KEY_COLUMN_USAGE`;
CREATE TABLE `KEY_COLUMN_USAGE`  (
  `CONSTRAINT_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLUMN_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ORDINAL_POSITION` bigint(10) NOT NULL DEFAULT 0,
  `POSITION_IN_UNIQUE_CONSTRAINT` bigint(10) NULL DEFAULT NULL,
  `REFERENCED_TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `REFERENCED_TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `REFERENCED_COLUMN_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for OPTIMIZER_TRACE
-- ----------------------------
DROP TABLE IF EXISTS `OPTIMIZER_TRACE`;
CREATE TABLE `OPTIMIZER_TRACE`  (
  `QUERY` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TRACE` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `MISSING_BYTES_BEYOND_MAX_MEM_SIZE` int(20) NOT NULL DEFAULT 0,
  `INSUFFICIENT_PRIVILEGES` tinyint(1) NOT NULL DEFAULT 0
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PARAMETERS
-- ----------------------------
DROP TABLE IF EXISTS `PARAMETERS`;
CREATE TABLE `PARAMETERS`  (
  `SPECIFIC_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SPECIFIC_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SPECIFIC_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ORDINAL_POSITION` int(21) NOT NULL DEFAULT 0,
  `PARAMETER_MODE` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PARAMETER_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DATA_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` int(21) NULL DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` int(21) NULL DEFAULT NULL,
  `NUMERIC_PRECISION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `NUMERIC_SCALE` int(21) NULL DEFAULT NULL,
  `DATETIME_PRECISION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CHARACTER_SET_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COLLATION_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DTD_IDENTIFIER` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ROUTINE_TYPE` varchar(9) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PARTITIONS
-- ----------------------------
DROP TABLE IF EXISTS `PARTITIONS`;
CREATE TABLE `PARTITIONS`  (
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PARTITION_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SUBPARTITION_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PARTITION_ORDINAL_POSITION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `SUBPARTITION_ORDINAL_POSITION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `PARTITION_METHOD` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SUBPARTITION_METHOD` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PARTITION_EXPRESSION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SUBPARTITION_EXPRESSION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `PARTITION_DESCRIPTION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `TABLE_ROWS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `AVG_ROW_LENGTH` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DATA_LENGTH` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `MAX_DATA_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `INDEX_LENGTH` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DATA_FREE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `CREATE_TIME` datetime NULL DEFAULT NULL,
  `UPDATE_TIME` datetime NULL DEFAULT NULL,
  `CHECK_TIME` datetime NULL DEFAULT NULL,
  `CHECKSUM` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `PARTITION_COMMENT` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `NODEGROUP` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLESPACE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PLUGINS
-- ----------------------------
DROP TABLE IF EXISTS `PLUGINS`;
CREATE TABLE `PLUGINS`  (
  `PLUGIN_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PLUGIN_VERSION` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PLUGIN_STATUS` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PLUGIN_TYPE` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PLUGIN_TYPE_VERSION` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PLUGIN_LIBRARY` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PLUGIN_LIBRARY_VERSION` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PLUGIN_AUTHOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PLUGIN_DESCRIPTION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `PLUGIN_LICENSE` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LOAD_OPTION` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PROCESSLIST
-- ----------------------------
DROP TABLE IF EXISTS `PROCESSLIST`;
CREATE TABLE `PROCESSLIST`  (
  `ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `USER` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `HOST` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DB` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COMMAND` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TIME` int(7) NOT NULL DEFAULT 0,
  `STATE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INFO` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PROFILING
-- ----------------------------
DROP TABLE IF EXISTS `PROFILING`;
CREATE TABLE `PROFILING`  (
  `QUERY_ID` int(20) NOT NULL DEFAULT 0,
  `SEQ` int(20) NOT NULL DEFAULT 0,
  `STATE` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DURATION` decimal(9, 6) NOT NULL DEFAULT 0.000000,
  `CPU_USER` decimal(9, 6) NULL DEFAULT NULL,
  `CPU_SYSTEM` decimal(9, 6) NULL DEFAULT NULL,
  `CONTEXT_VOLUNTARY` int(20) NULL DEFAULT NULL,
  `CONTEXT_INVOLUNTARY` int(20) NULL DEFAULT NULL,
  `BLOCK_OPS_IN` int(20) NULL DEFAULT NULL,
  `BLOCK_OPS_OUT` int(20) NULL DEFAULT NULL,
  `MESSAGES_SENT` int(20) NULL DEFAULT NULL,
  `MESSAGES_RECEIVED` int(20) NULL DEFAULT NULL,
  `PAGE_FAULTS_MAJOR` int(20) NULL DEFAULT NULL,
  `PAGE_FAULTS_MINOR` int(20) NULL DEFAULT NULL,
  `SWAPS` int(20) NULL DEFAULT NULL,
  `SOURCE_FUNCTION` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SOURCE_FILE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SOURCE_LINE` int(20) NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for REFERENTIAL_CONSTRAINTS
-- ----------------------------
DROP TABLE IF EXISTS `REFERENTIAL_CONSTRAINTS`;
CREATE TABLE `REFERENTIAL_CONSTRAINTS`  (
  `CONSTRAINT_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `UNIQUE_CONSTRAINT_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `UNIQUE_CONSTRAINT_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `UNIQUE_CONSTRAINT_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `MATCH_OPTION` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `UPDATE_RULE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DELETE_RULE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `REFERENCED_TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for ROUTINES
-- ----------------------------
DROP TABLE IF EXISTS `ROUTINES`;
CREATE TABLE `ROUTINES`  (
  `SPECIFIC_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ROUTINE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ROUTINE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ROUTINE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ROUTINE_TYPE` varchar(9) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DATA_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` int(21) NULL DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` int(21) NULL DEFAULT NULL,
  `NUMERIC_PRECISION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `NUMERIC_SCALE` int(21) NULL DEFAULT NULL,
  `DATETIME_PRECISION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CHARACTER_SET_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COLLATION_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DTD_IDENTIFIER` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ROUTINE_BODY` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ROUTINE_DEFINITION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `EXTERNAL_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `EXTERNAL_LANGUAGE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PARAMETER_STYLE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_DETERMINISTIC` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SQL_DATA_ACCESS` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SQL_PATH` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SECURITY_TYPE` varchar(7) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CREATED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_ALTERED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SQL_MODE` varchar(8192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ROUTINE_COMMENT` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DEFINER` varchar(93) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DATABASE_COLLATION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for SCHEMATA
-- ----------------------------
DROP TABLE IF EXISTS `SCHEMATA`;
CREATE TABLE `SCHEMATA`  (
  `CATALOG_NAME` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SCHEMA_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DEFAULT_CHARACTER_SET_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DEFAULT_COLLATION_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SQL_PATH` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for SCHEMA_PRIVILEGES
-- ----------------------------
DROP TABLE IF EXISTS `SCHEMA_PRIVILEGES`;
CREATE TABLE `SCHEMA_PRIVILEGES`  (
  `GRANTEE` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_GRANTABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for SESSION_STATUS
-- ----------------------------
DROP TABLE IF EXISTS `SESSION_STATUS`;
CREATE TABLE `SESSION_STATUS`  (
  `VARIABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `VARIABLE_VALUE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for SESSION_VARIABLES
-- ----------------------------
DROP TABLE IF EXISTS `SESSION_VARIABLES`;
CREATE TABLE `SESSION_VARIABLES`  (
  `VARIABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `VARIABLE_VALUE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for STATISTICS
-- ----------------------------
DROP TABLE IF EXISTS `STATISTICS`;
CREATE TABLE `STATISTICS`  (
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `NON_UNIQUE` bigint(1) NOT NULL DEFAULT 0,
  `INDEX_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `INDEX_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SEQ_IN_INDEX` bigint(2) NOT NULL DEFAULT 0,
  `COLUMN_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLLATION` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CARDINALITY` bigint(21) NULL DEFAULT NULL,
  `SUB_PART` bigint(3) NULL DEFAULT NULL,
  `PACKED` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NULLABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `INDEX_TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COMMENT` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INDEX_COMMENT` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for TABLES
-- ----------------------------
DROP TABLE IF EXISTS `TABLES`;
CREATE TABLE `TABLES`  (
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ENGINE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `VERSION` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `ROW_FORMAT` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TABLE_ROWS` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `AVG_ROW_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `MAX_DATA_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `INDEX_LENGTH` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_FREE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `AUTO_INCREMENT` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CREATE_TIME` datetime NULL DEFAULT NULL,
  `UPDATE_TIME` datetime NULL DEFAULT NULL,
  `CHECK_TIME` datetime NULL DEFAULT NULL,
  `TABLE_COLLATION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CHECKSUM` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `CREATE_OPTIONS` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TABLE_COMMENT` varchar(2048) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for TABLESPACES
-- ----------------------------
DROP TABLE IF EXISTS `TABLESPACES`;
CREATE TABLE `TABLESPACES`  (
  `TABLESPACE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ENGINE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLESPACE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LOGFILE_GROUP_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `EXTENT_SIZE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `AUTOEXTEND_SIZE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `MAXIMUM_SIZE` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `NODEGROUP_ID` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `TABLESPACE_COMMENT` varchar(2048) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for TABLE_CONSTRAINTS
-- ----------------------------
DROP TABLE IF EXISTS `TABLE_CONSTRAINTS`;
CREATE TABLE `TABLE_CONSTRAINTS`  (
  `CONSTRAINT_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CONSTRAINT_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for TABLE_PRIVILEGES
-- ----------------------------
DROP TABLE IF EXISTS `TABLE_PRIVILEGES`;
CREATE TABLE `TABLE_PRIVILEGES`  (
  `GRANTEE` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_GRANTABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for TRIGGERS
-- ----------------------------
DROP TABLE IF EXISTS `TRIGGERS`;
CREATE TABLE `TRIGGERS`  (
  `TRIGGER_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TRIGGER_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TRIGGER_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_MANIPULATION` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_OBJECT_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_OBJECT_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `EVENT_OBJECT_TABLE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ACTION_ORDER` bigint(4) NOT NULL DEFAULT 0,
  `ACTION_CONDITION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ACTION_STATEMENT` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ACTION_ORIENTATION` varchar(9) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ACTION_TIMING` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ACTION_REFERENCE_OLD_TABLE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ACTION_REFERENCE_NEW_TABLE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ACTION_REFERENCE_OLD_ROW` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ACTION_REFERENCE_NEW_ROW` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CREATED` datetime(2) NULL DEFAULT NULL,
  `SQL_MODE` varchar(8192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DEFINER` varchar(93) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DATABASE_COLLATION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for USER_PRIVILEGES
-- ----------------------------
DROP TABLE IF EXISTS `USER_PRIVILEGES`;
CREATE TABLE `USER_PRIVILEGES`  (
  `GRANTEE` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_GRANTABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for VIEWS
-- ----------------------------
DROP TABLE IF EXISTS `VIEWS`;
CREATE TABLE `VIEWS`  (
  `TABLE_CATALOG` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `VIEW_DEFINITION` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `CHECK_OPTION` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `IS_UPDATABLE` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `DEFINER` varchar(93) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SECURITY_TYPE` varchar(7) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for INNODB_LOCKS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_LOCKS`;
CREATE TABLE `INNODB_LOCKS`  (
  `lock_id` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `lock_trx_id` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `lock_mode` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `lock_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `lock_table` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `lock_index` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `lock_space` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `lock_page` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `lock_rec` bigint(21) UNSIGNED NULL DEFAULT NULL,
  `lock_data` varchar(8192) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_TRX
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_TRX`;
CREATE TABLE `INNODB_TRX`  (
  `trx_id` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `trx_state` varchar(13) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `trx_started` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `trx_requested_lock_id` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `trx_wait_started` datetime NULL DEFAULT NULL,
  `trx_weight` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_mysql_thread_id` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_query` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `trx_operation_state` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `trx_tables_in_use` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_tables_locked` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_lock_structs` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_lock_memory_bytes` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_rows_locked` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_rows_modified` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_concurrency_tickets` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_isolation_level` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `trx_unique_checks` int(1) NOT NULL DEFAULT 0,
  `trx_foreign_key_checks` int(1) NOT NULL DEFAULT 0,
  `trx_last_foreign_key_error` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `trx_adaptive_hash_latched` int(1) NOT NULL DEFAULT 0,
  `trx_adaptive_hash_timeout` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `trx_is_read_only` int(1) NOT NULL DEFAULT 0,
  `trx_autocommit_non_locking` int(1) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_DATAFILES
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_DATAFILES`;
CREATE TABLE `INNODB_SYS_DATAFILES`  (
  `SPACE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `PATH` varchar(4000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_FT_CONFIG
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_FT_CONFIG`;
CREATE TABLE `INNODB_FT_CONFIG`  (
  `KEY` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `VALUE` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_VIRTUAL
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_VIRTUAL`;
CREATE TABLE `INNODB_SYS_VIRTUAL`  (
  `TABLE_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `POS` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `BASE_POS` int(11) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_CMP
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_CMP`;
CREATE TABLE `INNODB_CMP`  (
  `page_size` int(5) NOT NULL DEFAULT 0,
  `compress_ops` int(11) NOT NULL DEFAULT 0,
  `compress_ops_ok` int(11) NOT NULL DEFAULT 0,
  `compress_time` int(11) NOT NULL DEFAULT 0,
  `uncompress_ops` int(11) NOT NULL DEFAULT 0,
  `uncompress_time` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_FT_BEING_DELETED
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_FT_BEING_DELETED`;
CREATE TABLE `INNODB_FT_BEING_DELETED`  (
  `DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_CMP_RESET
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_CMP_RESET`;
CREATE TABLE `INNODB_CMP_RESET`  (
  `page_size` int(5) NOT NULL DEFAULT 0,
  `compress_ops` int(11) NOT NULL DEFAULT 0,
  `compress_ops_ok` int(11) NOT NULL DEFAULT 0,
  `compress_time` int(11) NOT NULL DEFAULT 0,
  `uncompress_ops` int(11) NOT NULL DEFAULT 0,
  `uncompress_time` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_CMP_PER_INDEX
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_CMP_PER_INDEX`;
CREATE TABLE `INNODB_CMP_PER_INDEX`  (
  `database_name` varchar(192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `table_name` varchar(192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `index_name` varchar(192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `compress_ops` int(11) NOT NULL DEFAULT 0,
  `compress_ops_ok` int(11) NOT NULL DEFAULT 0,
  `compress_time` int(11) NOT NULL DEFAULT 0,
  `uncompress_ops` int(11) NOT NULL DEFAULT 0,
  `uncompress_time` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_CMPMEM_RESET
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_CMPMEM_RESET`;
CREATE TABLE `INNODB_CMPMEM_RESET`  (
  `page_size` int(5) NOT NULL DEFAULT 0,
  `buffer_pool_instance` int(11) NOT NULL DEFAULT 0,
  `pages_used` int(11) NOT NULL DEFAULT 0,
  `pages_free` int(11) NOT NULL DEFAULT 0,
  `relocation_ops` bigint(21) NOT NULL DEFAULT 0,
  `relocation_time` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_FT_DELETED
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_FT_DELETED`;
CREATE TABLE `INNODB_FT_DELETED`  (
  `DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_BUFFER_PAGE_LRU
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_BUFFER_PAGE_LRU`;
CREATE TABLE `INNODB_BUFFER_PAGE_LRU`  (
  `POOL_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LRU_POSITION` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `SPACE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGE_NUMBER` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FLUSH_TYPE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `FIX_COUNT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `IS_HASHED` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NEWEST_MODIFICATION` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `OLDEST_MODIFICATION` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `ACCESS_TIME` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `TABLE_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INDEX_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NUMBER_RECORDS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DATA_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `COMPRESSED_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `COMPRESSED` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IO_FIX` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IS_OLD` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FREE_PAGE_CLOCK` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_LOCK_WAITS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_LOCK_WAITS`;
CREATE TABLE `INNODB_LOCK_WAITS`  (
  `requesting_trx_id` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `requested_lock_id` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `blocking_trx_id` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `blocking_lock_id` varchar(81) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_TEMP_TABLE_INFO
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_TEMP_TABLE_INFO`;
CREATE TABLE `INNODB_TEMP_TABLE_INFO`  (
  `TABLE_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(202) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `N_COLS` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `SPACE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `PER_TABLE_TABLESPACE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IS_COMPRESSED` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_INDEXES
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_INDEXES`;
CREATE TABLE `INNODB_SYS_INDEXES`  (
  `INDEX_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TABLE_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `TYPE` int(11) NOT NULL DEFAULT 0,
  `N_FIELDS` int(11) NOT NULL DEFAULT 0,
  `PAGE_NO` int(11) NOT NULL DEFAULT 0,
  `SPACE` int(11) NOT NULL DEFAULT 0,
  `MERGE_THRESHOLD` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_TABLES
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_TABLES`;
CREATE TABLE `INNODB_SYS_TABLES`  (
  `TABLE_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(655) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FLAG` int(11) NOT NULL DEFAULT 0,
  `N_COLS` int(11) NOT NULL DEFAULT 0,
  `SPACE` int(11) NOT NULL DEFAULT 0,
  `FILE_FORMAT` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ROW_FORMAT` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ZIP_PAGE_SIZE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `SPACE_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_FIELDS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_FIELDS`;
CREATE TABLE `INNODB_SYS_FIELDS`  (
  `INDEX_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `POS` int(11) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_CMP_PER_INDEX_RESET
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_CMP_PER_INDEX_RESET`;
CREATE TABLE `INNODB_CMP_PER_INDEX_RESET`  (
  `database_name` varchar(192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `table_name` varchar(192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `index_name` varchar(192) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `compress_ops` int(11) NOT NULL DEFAULT 0,
  `compress_ops_ok` int(11) NOT NULL DEFAULT 0,
  `compress_time` int(11) NOT NULL DEFAULT 0,
  `uncompress_ops` int(11) NOT NULL DEFAULT 0,
  `uncompress_time` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_BUFFER_PAGE
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_BUFFER_PAGE`;
CREATE TABLE `INNODB_BUFFER_PAGE`  (
  `POOL_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `BLOCK_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `SPACE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGE_NUMBER` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGE_TYPE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FLUSH_TYPE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `FIX_COUNT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `IS_HASHED` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NEWEST_MODIFICATION` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `OLDEST_MODIFICATION` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `ACCESS_TIME` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `TABLE_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INDEX_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NUMBER_RECORDS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DATA_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `COMPRESSED_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGE_STATE` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IO_FIX` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IS_OLD` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FREE_PAGE_CLOCK` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_FT_DEFAULT_STOPWORD
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_FT_DEFAULT_STOPWORD`;
CREATE TABLE `INNODB_FT_DEFAULT_STOPWORD`  (
  `value` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_FT_INDEX_TABLE
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_FT_INDEX_TABLE`;
CREATE TABLE `INNODB_FT_INDEX_TABLE`  (
  `WORD` varchar(337) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FIRST_DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LAST_DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DOC_COUNT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `POSITION` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_FT_INDEX_CACHE
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_FT_INDEX_CACHE`;
CREATE TABLE `INNODB_FT_INDEX_CACHE`  (
  `WORD` varchar(337) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FIRST_DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LAST_DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DOC_COUNT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DOC_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `POSITION` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_TABLESPACES
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_TABLESPACES`;
CREATE TABLE `INNODB_SYS_TABLESPACES`  (
  `SPACE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(655) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FLAG` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `FILE_FORMAT` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ROW_FORMAT` varchar(22) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PAGE_SIZE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `ZIP_PAGE_SIZE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `SPACE_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FS_BLOCK_SIZE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `FILE_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `ALLOCATED_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_METRICS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_METRICS`;
CREATE TABLE `INNODB_METRICS`  (
  `NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `SUBSYSTEM` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COUNT` bigint(21) NOT NULL DEFAULT 0,
  `MAX_COUNT` bigint(21) NULL DEFAULT NULL,
  `MIN_COUNT` bigint(21) NULL DEFAULT NULL,
  `AVG_COUNT` double NULL DEFAULT NULL,
  `COUNT_RESET` bigint(21) NOT NULL DEFAULT 0,
  `MAX_COUNT_RESET` bigint(21) NULL DEFAULT NULL,
  `MIN_COUNT_RESET` bigint(21) NULL DEFAULT NULL,
  `AVG_COUNT_RESET` double NULL DEFAULT NULL,
  `TIME_ENABLED` datetime NULL DEFAULT NULL,
  `TIME_DISABLED` datetime NULL DEFAULT NULL,
  `TIME_ELAPSED` bigint(21) NULL DEFAULT NULL,
  `TIME_RESET` datetime NULL DEFAULT NULL,
  `STATUS` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `TYPE` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `COMMENT` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_FOREIGN_COLS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_FOREIGN_COLS`;
CREATE TABLE `INNODB_SYS_FOREIGN_COLS`  (
  `ID` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FOR_COL_NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `REF_COL_NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `POS` int(11) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_CMPMEM
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_CMPMEM`;
CREATE TABLE `INNODB_CMPMEM`  (
  `page_size` int(5) NOT NULL DEFAULT 0,
  `buffer_pool_instance` int(11) NOT NULL DEFAULT 0,
  `pages_used` int(11) NOT NULL DEFAULT 0,
  `pages_free` int(11) NOT NULL DEFAULT 0,
  `relocation_ops` bigint(21) NOT NULL DEFAULT 0,
  `relocation_time` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_BUFFER_POOL_STATS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_BUFFER_POOL_STATS`;
CREATE TABLE `INNODB_BUFFER_POOL_STATS`  (
  `POOL_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `POOL_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `FREE_BUFFERS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `DATABASE_PAGES` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `OLD_DATABASE_PAGES` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `MODIFIED_DATABASE_PAGES` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PENDING_DECOMPRESS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PENDING_READS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PENDING_FLUSH_LRU` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PENDING_FLUSH_LIST` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGES_MADE_YOUNG` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGES_NOT_MADE_YOUNG` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGES_MADE_YOUNG_RATE` double NOT NULL DEFAULT 0,
  `PAGES_MADE_NOT_YOUNG_RATE` double NOT NULL DEFAULT 0,
  `NUMBER_PAGES_READ` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NUMBER_PAGES_CREATED` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NUMBER_PAGES_WRITTEN` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `PAGES_READ_RATE` double NOT NULL DEFAULT 0,
  `PAGES_CREATE_RATE` double NOT NULL DEFAULT 0,
  `PAGES_WRITTEN_RATE` double NOT NULL DEFAULT 0,
  `NUMBER_PAGES_GET` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `HIT_RATE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `YOUNG_MAKE_PER_THOUSAND_GETS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NOT_YOUNG_MAKE_PER_THOUSAND_GETS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NUMBER_PAGES_READ_AHEAD` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NUMBER_READ_AHEAD_EVICTED` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `READ_AHEAD_RATE` double NOT NULL DEFAULT 0,
  `READ_AHEAD_EVICTED_RATE` double NOT NULL DEFAULT 0,
  `LRU_IO_TOTAL` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LRU_IO_CURRENT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `UNCOMPRESS_TOTAL` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `UNCOMPRESS_CURRENT` bigint(21) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_COLUMNS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_COLUMNS`;
CREATE TABLE `INNODB_SYS_COLUMNS`  (
  `TABLE_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `POS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `MTYPE` int(11) NOT NULL DEFAULT 0,
  `PRTYPE` int(11) NOT NULL DEFAULT 0,
  `LEN` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_FOREIGN
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_FOREIGN`;
CREATE TABLE `INNODB_SYS_FOREIGN`  (
  `ID` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `FOR_NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `REF_NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `N_COLS` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `TYPE` int(11) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for INNODB_SYS_TABLESTATS
-- ----------------------------
DROP TABLE IF EXISTS `INNODB_SYS_TABLESTATS`;
CREATE TABLE `INNODB_SYS_TABLESTATS`  (
  `TABLE_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `NAME` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `STATS_INITIALIZED` varchar(193) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `NUM_ROWS` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `CLUST_INDEX_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `OTHER_INDEX_SIZE` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `MODIFIED_COUNTER` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `AUTOINC` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `REF_COUNT` int(11) NOT NULL DEFAULT 0
) ENGINE = MEMORY CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Fixed;

SET FOREIGN_KEY_CHECKS = 1;
